name: apk-build

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'release/*'
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'release/*'
  workflow_dispatch:
    inputs:
      build-description:
        description: 'Build info'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker-compose --file docker-compose.android.yml up
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-result
          path: |
            ./android/reminder.apk
          retention-days: 30

